### ISSUE TITLE
Castling is not supported

### ISSUE THREAD

**Issue by KarolisL** [KTUBoys/ChessMP#18]
https://en.wikipedia.org/wiki/Castling

This if a blocker for me and my team to use your product. Castling is an essential for me to be able to execute this pro gamer move. 

We have lost millions of billions already because of this lack of essential features. Please fix ASAP, or we will sue.

**Comment by CrabbyLT** [comment]
As I have mentioned before, the game has very basic chess piece logic implemented. We work hard and castling should be supported in a near future
