### ISSUE TITLE
No support for multiplayer over network.

### ISSUE THREAD

**Issue by hcbt** [KTUBoys/ChessMP#21]
I would love to play this over lan with my co-workers during our work hours unfortunately I couldn’t find a way to set up a server and apparently multiplayer only works on the same computer?! Plz help.

**Comment by CrabbyLT** [comment]
The online feature is still in the works, this is not a full release of the game. Hopefully next update will have some sort of online multiplayer feature implemented. Thanks for the feedback 👍
